# Generated by Django 5.2.14 on 2026-05-16 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('explanations', '0004_add_use_compensatory_to_explanation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompensatoryBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_hours', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('used_hours', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compensatory_balance', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Số giờ nghỉ bù',
            },
        ),
        migrations.CreateModel(
            name='CompensatoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('credit', 'Cấp bù'), ('debit', 'Dùng bù')], max_length=10)),
                ('hours', models.DecimalField(decimal_places=1, max_digits=4)),
                ('date', models.DateField()),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='employees.compensatorybalance')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compensatory_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensatory_transactions', to='employees.employee')),
                ('explanation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compensatory_transaction', to='explanations.explanation')),
            ],
            options={
                'verbose_name': 'Giao dịch nghỉ bù',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
