# Generated by Django 5.2.14 on 2026-05-16 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_add_compensatory_balance_transaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compensatorybalance',
            options={'verbose_name': 'Số giờ nghỉ bù', 'verbose_name_plural': 'Số giờ nghỉ bù'},
        ),
        migrations.AlterModelOptions(
            name='compensatorytransaction',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Giao dịch nghỉ bù', 'verbose_name_plural': 'Giao dịch nghỉ bù'},
        ),
        migrations.AlterField(
            model_name='compensatorytransaction',
            name='hours',
            field=models.DecimalField(decimal_places=1, max_digits=6),
        ),
    ]
