# Generated by Django 5.2.14 on 2026-05-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_leavebalance_used_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compensatorytransaction',
            name='transaction_type',
            field=models.CharField(choices=[('credit', 'Cấp bù'), ('debit', 'Dùng bù'), ('provisional', 'Dự kiến trừ bù')], max_length=15),
        ),
    ]
