# Generated by Django 5.2.14 on 2026-05-08 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explanations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='explanation',
            name='note',
        ),
        migrations.RemoveField(
            model_name='explanation',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='explanation',
            name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='explanation',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='explanation',
            name='reviewer_note',
        ),
        migrations.RemoveField(
            model_name='explanation',
            name='status',
        ),
        migrations.AddField(
            model_name='explanation',
            name='ci_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='explanation',
            name='ci_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ci_explanations', to='explanations.explanationreason'),
        ),
        migrations.AddField(
            model_name='explanation',
            name='ci_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='explanation',
            name='ci_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ci_reviewed_explanations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='explanation',
            name='ci_reviewer_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='explanation',
            name='ci_status',
            field=models.CharField(blank=True, choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='explanation',
            name='co_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='explanation',
            name='co_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='co_explanations', to='explanations.explanationreason'),
        ),
        migrations.AddField(
            model_name='explanation',
            name='co_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='explanation',
            name='co_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='co_reviewed_explanations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='explanation',
            name='co_reviewer_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='explanation',
            name='co_status',
            field=models.CharField(blank=True, choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='explanationreason',
            name='requires_full_day_shift',
            field=models.BooleanField(default=False),
        ),
    ]
