# Generated by Django 5.2.14 on 2026-05-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explanations', '0002_remove_explanation_note_remove_explanation_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='explanationreason',
            name='is_compensatory',
            field=models.BooleanField(default=False),
        ),
    ]
