# Generated by Django 5.2.14 on 2026-05-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explanations', '0003_add_is_compensatory_to_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='explanation',
            name='ci_use_compensatory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='explanation',
            name='co_use_compensatory',
            field=models.BooleanField(default=False),
        ),
    ]
