# Generated by Django 5.2.14 on 2026-05-08 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=7)),
                ('actual_workdays', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('leave_days_used', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('finalized', 'Đã chốt')], default='draft', max_length=20)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('calculated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculations', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Kết quả tính công',
                'ordering': ['employee__code'],
                'unique_together': {('employee', 'month')},
            },
        ),
    ]
