# Generated by Django 5.2.14 on 2026-05-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancecalculation',
            name='leave_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='attendancecalculation',
            name='work_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='attendancecalculation',
            name='actual_workdays',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='attendancecalculation',
            name='leave_days_used',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
