# Generated by Django 5.2.14 on 2026-05-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Ký hiệu ca')),
                ('check_in', models.TimeField(blank=True, null=True, verbose_name='Giờ vào')),
                ('check_out', models.TimeField(blank=True, null=True, verbose_name='Giờ ra')),
                ('total_hours', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Tổng giờ')),
                ('workday_value', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='Ngày công')),
                ('leave_day_value', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='Ngày phép')),
                ('work_hours', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Giờ công')),
                ('leave_hours', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Giờ phép')),
                ('break_start', models.TimeField(blank=True, null=True, verbose_name='Bắt đầu nghỉ trưa')),
                ('break_end', models.TimeField(blank=True, null=True, verbose_name='Kết thúc nghỉ trưa')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ca làm việc',
                'verbose_name_plural': 'Ca làm việc',
                'ordering': ['code'],
            },
        ),
    ]
