# Generated by Django 5.2.14 on 2026-05-08 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_add_shift_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='minutes_early',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='minutes_late',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='shift_code',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
