version = 5.6.0
archive_dir = /etc/letsencrypt/archive/yduocsaophuongdong.site
cert = /etc/letsencrypt/live/yduocsaophuongdong.site/cert.pem
privkey = /etc/letsencrypt/live/yduocsaophuongdong.site/privkey.pem
chain = /etc/letsencrypt/live/yduocsaophuongdong.site/chain.pem
fullchain = /etc/letsencrypt/live/yduocsaophuongdong.site/fullchain.pem
[renewalparams]
account = 25728f7a253dd1d7510b1277b8977208
pref_challs = dns-01,
authenticator = manual
manual_auth_hook = /tmp/auth-hook.sh
manual_cleanup_hook = echo cleanup
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
